# Generated by Django 5.2 on 2025-05-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(unique=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('sucursal', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMarcaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('marca_entrada', models.TimeField()),
                ('marca_salida', models.TimeField()),
                ('simbolo', models.CharField(blank=True, null=True)),
                ('falta', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcaje.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Marcaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_registro', models.CharField(choices=[('I', 'Entrada'), ('O', 'Salida')], max_length=1)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcaje.empleado')),
            ],
            options={
                'indexes': [models.Index(fields=['id_externo'], name='marcaje_mar_id_exte_8f92da_idx'), models.Index(fields=['empleado', 'fecha_hora'], name='marcaje_mar_emplead_f7cac2_idx')],
                'unique_together': {('id_externo', 'empleado', 'fecha_hora')},
            },
        ),
    ]
