# Generated by Django 5.2 on 2025-05-02 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcaje',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Registro de marcaje', 'verbose_name_plural': 'Registros de marcaje'},
        ),
        migrations.RemoveIndex(
            model_name='marcaje',
            name='marcaje_mar_id_exte_8f92da_idx',
        ),
        migrations.AlterUniqueTogether(
            name='marcaje',
            unique_together={('empleado', 'fecha_hora', 'tipo_registro')},
        ),
        migrations.AlterField(
            model_name='marcaje',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcaje.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='marcaje',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y hora de registro'),
        ),
        migrations.AlterField(
            model_name='marcaje',
            name='tipo_registro',
            field=models.CharField(choices=[('I', 'Entrada'), ('O', 'Salida')], max_length=1, verbose_name='Tipo de marcaje'),
        ),
        migrations.RemoveField(
            model_name='marcaje',
            name='id_externo',
        ),
    ]
