# Generated by Django 5.2 on 2025-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registromarcaje',
            options={},
        ),
        migrations.AlterField(
            model_name='registromarcaje',
            name='falta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registromarcaje',
            name='simbolo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
