# Generated by Django 5.2 on 2025-04-25 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sucursal', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='registromarcaje',
            old_name='hora_salida',
            new_name='marca_entrada',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='registromarcaje',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='registromarcaje',
            name='tipo_marcaje',
        ),
        migrations.AddField(
            model_name='empleado',
            name='horaentrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horasalida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromarcaje',
            name='falta',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromarcaje',
            name='marca_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromarcaje',
            name='simbolo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='registromarcaje',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marcaje.departamentos'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marcaje.sucursal'),
        ),
    ]
