# Generated by Django 5.2 on 2025-05-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcajeBruto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('marca_entrada', models.TimeField(null=True)),
                ('marca_salida', models.TimeField(null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcaje.empleado')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroMarcaje',
        ),
    ]
