# Generated by Django 5.2 on 2025-05-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0002_alter_marcaje_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcaje',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='marcaje',
            name='marcaje_mar_emplead_f7cac2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='marcaje',
            unique_together=set(),
        ),
    ]
