# Generated by Django 5.2 on 2025-05-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0002_marcajebruto_delete_registromarcaje'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarcajeBruto',
            new_name='MarcajeDepurado',
        ),
    ]
