# Generated by Django 5.2 on 2025-05-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0003_rename_marcajebruto_marcajedepurado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcajedepurado',
            old_name='marca_entrada',
            new_name='entrada',
        ),
        migrations.RenameField(
            model_name='marcajedepurado',
            old_name='marca_salida',
            new_name='salida',
        ),
    ]
