# Generated by Django 5.2 on 2025-05-06 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0004_rename_marca_entrada_marcajedepurado_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_permiso', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('fecha_solicitud', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('comprobante', models.FileField(upload_to='')),
                ('estado_solicitud', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('A', 'Rechazada')])),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcaje.empleado')),
            ],
        ),
    ]
